### ISSUE TITLE
您好，能否贴一下如何引入android和ios

### ISSUE THREAD

**Issue by tyao1** [lvbingru/react-native-pingxx#1]
如题。您的ping++组建应该是现在开源的最好的react naitve ping++组建了，如果能贴一下如何配置就更好了。非常感谢！

**Comment by lekenny** [comment]
@xiaobuu  你那个是直接可以使用的嘛

**Comment by tyao1** [comment]
@lekenny 可以用额 用rnpm link一下好像就好，忘记还要配置什么了，反正缺的配置参照官方sdk的说明配就好了。
